import { Inter, DM_Sans, DM_Serif_Display } from "next/font/google";
import "./globals.css";

const dm_sans = DM_Sans({ subsets: ["latin"]});

const dm_serif_display = DM_Serif_Display( { 
  subsets: ["latin"],
  weight: '400',
  variable: '--font-dm-serif'
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${dm_sans.className} ${dm_serif_display.variable}`}>{children}</body>
    </html>
  );
}
